# Generated by Django 3.1.13 on 2021-09-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyndril', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='resident',
        ),
    ]
